### ISSUE TITLE
NoClassDefFoundError: Failed resolution of: Ljava/lang/management/ManagementFactory on Android

### ISSUE THREAD

**Issue by Augusent** [reactor/BlockHound#11]
I'm getting an exception with the following setup: 
```
debugImplementation "io.projectreactor.tools:blockhound:1.0.0.M1"
```
```
if (BuildConfig.DEBUG && Build.VERSION.SDK_INT >= Build.VERSION_CODES.N) {
            BlockHound.builder()
                .nonBlockingThreadPredicate { current -> current.or { it === Looper.getMainLooper().thread } }
                .install()
        }
```
Just a quick search gives a similar issue for Mockito: https://github.com/mockito/mockito/issues/841
Can this library be used on Android in theory?

**Comment by bsideup** [comment]
Hi @Augusent,

Since the BlockHound library is based on the instrumentation, I assume it can't be used on Android as Rafael mentioned here:
https://github.com/mockito/mockito/issues/841#issuecomment-269125686

However, you can run unit tests with a normal JVM to check that your code does not use blocking methods.
