### ISSUE TITLE
Suggestion: publish dependencies in pom.xml

### ISSUE THREAD

**Issue by suztomo** [reactor/BlockHound#99]
Our static analysis tool (Linkage Checker) detected Maven artifact `io.projectreactor.tools:blockhound:1.0.1.RELEASE` has missing dependencies (https://github.com/GoogleCloudPlatform/cloud-opensource-java/pull/1286) in its pom.xml.

https://search.maven.org/artifact/io.projectreactor.tools/blockhound/1.0.1.RELEASE/jar

<img width="1135" alt="Screen Shot 2020-03-13 at 13 13 13" src="https://user-images.githubusercontent.com/28604/76643933-6c68df00-652c-11ea-8cc6-8bfdf44b7e79.png">

Would you declare blockhound's dependencies in pom.xml?

**Comment by bsideup** [comment]
Hi @suztomo,

Thanks for reporting! Interesting tool!

We have these defined as `compileOnly` since we integrate with them only when classes are available on classpath:
https://github.com/reactor/BlockHound/blob/174ef41890b6c582b47ba84fbfe034fa7b419da4/agent/build.gradle#L59

The dependencies section is empty because we shade the rest of dependencies that are needed for BlockHound to operate.

It looks like the analysis tool gives a false positive result here (given that it works correctly at runtime), unless I miss something.

**Comment by suztomo** [comment]
Thank you for explanation.

> when classes are available on classpath

From BlockHound’s pom.xml in Maven Central, it’s unclear which Maven artifact your users should pick if they want to supply the classes. I suggest declaring it as “optional”. What do you think?

**Comment by bsideup** [comment]
@suztomo the thing is - we integrate with user's "environment", the user does not need to know which classes should be there, it is rather "if they are available, we do our thing".

Adding it as optional dependencies would be slightly misleading because _we_ don't need them, and _our_ behaviour won't change if user adds any of them.

**Comment by suztomo** [comment]
@bsideup Thank you for explanation. My suggestion does not apply to such case of "if they are available, we do our thing".

**Comment by bsideup** [comment]
@suztomo thanks for sharing the problem!
Let us know if we can do anything reasonable on our side to make it easier for your tool to analyze, we would be happy to help!
